py/ybook/ch4/bookmark/urls.py
from django.urls import path
from .views import BookMarkListView, BookMarkCreateView, BookMarkDetailView, BookMarkUpdateView,BookMarkDeleteView
app_name='bookmark'
urlpatterns = [
    path('', BookMarkListView.as_view(), name='list'),
    path('add/', BookMarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>/', BookMarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookMarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookMarkDeleteView.as_view(), name='delete'),
]

py/ybook/ch4/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
]

py/ybook/ch4/bookmark/models.py
from django.db import models

# Create your models here.
class BookMark(models.Model):
    site_name = models.CharField(max_length=100)
    url=models.URLField('Site URL')
    def __str__(self):
        #객체를 출력할 때 나타날 값:
        return "이름: "+self.site_name+", 주소: "+self.url

py/ybook/ch4/bookmark/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import BookMark

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse

from django.views.generic.detail import DetailView

from django.views.generic.edit import UpdateView

from django.views.generic.edit import DeleteView
# Create your views here.
class BookMarkListView(ListView):
    model = BookMark
    paginate_by = 6

class BookMarkCreateView(CreateView):
    model = BookMark
    fields = ['site_name', 'url']
    success_url = reverse_lazy("bookmark:list")
    template_name_suffix = '_create'

class BookMarkDetailView(DetailView):
    model=BookMark

class BookMarkUpdateView(UpdateView):
    model = BookMark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'
    success_url = reverse_lazy("bookmark:list")

class BookMarkDeleteView(DeleteView):
    model=BookMark
    success_url = reverse_lazy('bookmark:list')

py/ybook/ch4/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Confirm Delete{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{ object }}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
{% endblock %}

py/ybook/ch4/bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}
BookMark add
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="add" class="btn btn-info btn-sm">
    </form>
{% endblock %}

py/ybook/ch4/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
    {{ object.site_name }}<br>
    {{ object.url }}
{% endblock %}

py/ybook/ch4/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}
Bookmark List
{% endblock %}
{% block content %}
    <div class="btn-group">
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
    </div>
    <p></p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Site</th>
                <th scope="col">URL</th>
                <th scope="col">Modify</th>
                <th scope="col">Delete</th>

            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
                <td><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></td>
                <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block pagination %}
    {% if is_paginated %}
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.previous_number }}"
                   tabindex="-1">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        {% endif %}

        {% for object in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
                <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
            </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        {% endif %}
    </ul>
    {% endif %}
{% endblock %}

py/ybook/ch4/bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}
Bookmark update
{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update" class="btn btn-info btn-sm">
{% endblock %}

py/ybook/ch4/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Django Bookmark</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mr-auto">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <p></p>
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
                {% block pagination %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>